### ISSUE TITLE
cannot still install vagrant-berkshelf after installing chefDK

### ISSUE THREAD

**Issue by xs3c** [berkshelf/vagrant-berkshelf#290] opened 2015-07-13 09:32 UTC
@sethvargo,

I ran into a trouble while installing vagrant-berkshelf on ubuntu 14.04. Firstly install vagrant-berkshelf, it hinted me to install chefDK, so I downloaded and then installed it.

> wyang@wyang-Lenovo-Y430P:/opt/chefdk/bin$ ls
> berks  chef  chef-apply  chef-client  chef-service-manager  chef-shell  chef-solo  chef-vault  chef->windows-service  fauxhai  foodcritic  kitchen  knife  ohai  rubocop

I also add the installed path of chefdk  to my bashrc profile.

> wyang@wyang-Lenovo-Y430P:/opt/chefdk/bin$ echo $PATH
> /opt/packer/:/opt/chefdk/bin:/opt/ceph/bin:/home/wyang/bin:/opt/qemu/bin/:/home/wyang/bin:/usr/local/s>bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

But unfortunately I still got the following error:

> wyang@wyang-Lenovo-Y430P:/opt/chefdk/bin$ vagrant plugin install vagrant-berkshelf
> Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
> Installed the plugin 'vagrant-berkshelf (4.0.4)'!
> Post install message from the 'vagrant-berkshelf' plugin:
> The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
> You can download the latest version of the Chef Development Kit from:
>    https://downloads.getchef.com/chef-dk
> Installing Berkshelf via other methods is not officially supported.

The following is my related software version information.

> wyang@wyang-Lenovo-Y430P:/opt/chefdk/bin$ chef -v
> Chef Development Kit Version: 0.6.2
> chef-client version: 12.3.0
> berks version: 3.2.4
> kitchen version: 1.4.0
> wyang@wyang-Lenovo-Y430P:/opt/chefdk/bin$ vagrant -v
> Vagrant 1.7.3

**Comment by se77en** [comment] 2015-07-26 14:19
same to me, so sad

**Comment by DrickDidick** [comment] 2015-08-14 15:22
I have the same issue

**Comment by najamelan** [comment] 2015-11-03 17:16
on debian also have this problem after installing the deb from chefdk

**Comment by jstarcher** [comment] 2016-01-07 16:37
wow, just realized after spinning my wheels on this as well that the message comes from spec.post_install_message. If you run `vagrant plugin list` I bet the was installed.

**Comment by emiviada** [comment] 2016-06-17 17:04
@jstarcher is right. The plugin installation keeps showing that message, but the plugin is installed. You can check it with: `vagrant plugin list`

**Comment by naiduarvind** [comment] 2016-10-04 06:56
Just verified what @jstarcher and @emiviada said. It seems to be installed when checked against the plugin list but when trying to install, it say it is not. Yet to see if it runs with vagrant up.
<img width="1440" alt="screen shot 2016-10-04 at 2 54 32 pm" src="https://cloud.githubusercontent.com/assets/6829472/19064869/a8571bbc-8a42-11e6-9998-558f81624853.png">

**Comment by thommay** [comment] 2016-12-06 14:15
Duplicate of #299 ; the plugin is installed fine.

**Closed by thommay** 2016-12-06 14:15 UTC
